import '@styles/global.css';
import Nav from '@components/Nav';
import Provider from '@components/Provider';

export const metadata = {
  title: 'Promptopia the great one',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <Provider>
        <Nav/>

        <div className='main'>
          <div className='gradient'/>
        </div>
        <main className='app'>
        {children}
        </main>
        </Provider>
        </body>
    </html>
  )
}
